development: 
  host: 127.0.0.1
  username: Dan
  adapter: postgresql
  database: scrive_dev
  encoding: unicode

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
